name: TEST SSH

on:
  push:
    branches:
      - main # 触发条件，可以根据需要修改

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 检出代码，包括 deploy.sh 文件
      - name: Debug Secrets
        run: echo "Host is:${{ secrets.ALIYUN_HOST }}"

      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          script: |
            echo "ssh 连接成功"
